name = "dots-and-boxes"
main = "src/worker.ts"
compatibility_date = "2025-02-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [{ name = "GAME_ROOM", class_name = "GameRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
